### PR TITLE
Transition to nix-gaming

### PR DESCRIPTION
**Pull request by fufexan**
This repo is currently limited to osu!, but it may serve as a good home for other games. Especially since `wine-tkg` can serve a lot of them due to its versatility.

This is a proposal to rename the repo `nix-gaming` and add more games in the future (follow up to this PR will be Rocket League and Technic Launcher; they are currently in my dotfiles). Roblox (grapejuice) may come as well.

Currently many names have to be changed, but I'll be quick to move everything over once I get approvals.

I'll also have to reference [nixGL](https://github.com/guibou/nixGL) for those who choose to play on non-NixOS distros.

### CODE REVIEW

**Review by shadowninja55 — APPROVED** [review]
i agree with this decision :+1:.

**Comment by Artturin** [comment]
grapejuice is in nixpkgs (added by me)

**Comment by fufexan** [comment]
@Artturin I know, but what I plan to do is add an override to it so it can use `wine-tkg`. Along with it, I'll add the mouse patch to `wine-tkg`, and it *supposedly* gets rid of lag and mouse problems in Roblox.

**Comment by fufexan** [comment]
I have thought about the decision to rename this repo, but I've had another idea - create another repo continuing this one's history, and marking this one as archived. This way, I don't break users' configurations *yet*. There *will* be changes to `osu-stable` that some users may want, that will only be available in the new repo.

Thoughts?

**Comment by shadowninja55** [comment]
> I have thought about the decision to rename this repo, but I've had another idea - create another repo continuing this one's history, and marking this one as archived. This way, I don't break users' configurations _yet_. There _will_ be changes to `osu-stable` that some users may want, that will only be available in the new repo.
> 
> Thoughts?

agreed, it's probably not ideal for users to see errors after they `nix flake update`.

**Comment by fufexan** [comment]
Created the new repo at https://github.com/fufexan/nix-gaming.

Gonna slowly archive this repo and point it to the new one.

**Pull request closed without merging**
